######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 7 11:47:06 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += link_pkgconfig
PKGCONFIG += gstreamer-interfaces-0.10 gstreamer-0.10
# Input
HEADERS += qtcam0.h
SOURCES += main.cpp qtcam0.cpp
