######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 6 19:53:54 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += link_pkgconfig
PKGCONFIG += gstreamer-video-1.0 gstreamer-1.0

# Input
HEADERS += qtcam1.h
SOURCES += main.cpp qtcam1.cpp
