######################################################################
# Automatically generated by qmake (3.0) Sat Aug 6 19:56:19 2016
######################################################################

TEMPLATE = app
TARGET = qtcam1
INCLUDEPATH += .

# Input
HEADERS += qtcam1.h
SOURCES += main.cpp qtcam1.cpp
QT += widgets
CONFIG += link_pkgconfig
PKGCONFIG += gstreamer-video-1.0 gstreamer-1.0
